# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-zonaprop
dependencies:
  - python=3.9
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - pip:
    - lxml
    - numpy
    - requests
    - matplotlib
    - transformers
    - pandas
    - ragatouille
    - tiktoken
    - openai
    - langchain
    - llama-index
    - streamlit
    - gradio